# Generated by Django 2.1.2 on 2018-10-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('TH', 'Thriller'), ('CO', 'Comedy'), ('RM', 'Romance'), ('AD', 'Adventure'), ('FC', 'Fiction'), ('SF', 'Sci-Fi')], max_length=20)),
                ('lang', models.CharField(choices=[('EN', 'English'), ('SP', 'Spanish'), ('FR', 'French')], max_length=12)),
                ('rented', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_rental.customer'),
        ),
    ]
