# Generated by Django 2.1.2 on 2018-10-31 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental', '0002_auto_20181030_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_rental.customer'),
        ),
    ]
