# Generated by Django 2.1.2 on 2018-11-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental', '0003_auto_20181031_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
    ]
